postgres:
  debug: false
  host: 127.0.0.1
  user: postgres
  port: 15432
  pass: 123456
  database: sys_security
redis:
  host: 127.0.0.1:6379
  pass: 123456
  db: 0
server:
  mode: allow
  name: Auth
  host: 127.0.0.1
  port: 8080
captcha:
  key-long:
  img-width:
  img-height:
  open-captcha:
  open-captcha-timeout:
jwt:
  signKey:
  bufferTime:
  expiresTime:
casbin:
  modelName: rbac
zap:
  level: info
  prefix: [worframe/test]
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true
