name: Auth
host: 127.0.0.1
port: 8080
postgres:
  host: 127.0.0.1
  user: postgres
  port: 15432
  pass: 123456
  database: test
redis:
  host: 127.0.0.1:6379
  pass: 123456
  db: 0
server:
  mode: allow
  secret: ExpressMongodbNodejsReact
  bufferTime: 1d
  expireTime: 7d