postgres:
  debug: true
  host: 127.0.0.1
  user: postgres
  port: 15432
  pass: 123456
  database: test
redis:
  host: 127.0.0.1:16379
  pass: 123456
  db: 0
server:
  mode: allow
  name: Auth
  host: 127.0.0.1
  port: 8080
captcha:
  key-long:
  img-width:
  img-height:
  open-captcha:
  open-captcha-timeout:
jwt:
  signKey: Js1U5GC0jclCFJHfLCq3LxViIw7U4/4n0i6dT2X2v80=
  bufferTime: 24h
  expiresTime: 24h
casbin:
  modelName: rbacWithPattern
zap:
  director: log
  log-in-console: true
  max-backups: 10
  max-size: 10
  max-age: 28