version: 33
jobs:
- name: sync github
  steps:
  - !PushRepository
    name: github
    remoteUrl: https://github.com/haiziohhue/worframe.git
    userName: haiziohhue
    passwordSecret: access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    projects: worframe
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
